version: '3'

services:
  traefik:
    # The latest official supported Traefik docker image
    image: traefik:v2.3
    # Enables the Traefik Dashboard and tells Traefik to listen to docker
    # enable --log.level=INFO so we can see what Traefik is doing in the log files
    ports:
      # Exposes port 80 for incoming web requests
      - "80:80"
      # The Web UI port http://0.0.0.0:8080 (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml

# Add the whoami service
  saveww:
     # A container that exposes an API to show its IP address
     image: lorenzouriel147/save-ww:v1
     # We set a label to tell Traefik to assign a hostname to the new service
     labels:
       - "traefik.enable=true"
      # Routers
       - "traefik.http.routers.saveww.rule=Host(`saveww.localhost`)"
       - "traefik.http.routers.saveww.service=saveww"
       - "traefik.http.routers.saveww.entrypoints=web"
       - "traefik.http.routers.saveww.middlewares=saveww-auth,saveww-compress,saveww-errorpages,saveww-ratelimit, saveww-retry"
      # Services
       - "traefik.http.services.saveww.loadbalancer.server.port=80"
      # Middleware BasicAuth
       - "traefik.http.middlewares.saveww-auth.basicauth.users=whoisheisenberg:$$apr1$$oP8nSKa.$$TITERRdBsJCxX7VkfB8WL1"
        # Password: whoisheisenberg walterwhite
      # Compress Middleware
       - "traefik.http.middlewares.saveww-compress.compress=true"
      # Error Pages Middleware
       - "traefik.http.middlewares.saveww-errorpages.errors.status=400-599"
       - "traefik.http.middlewares.saveww-errorpages.errors.service=error"
       - "traefik.http.middlewares.saveww-errorpages.errors.query=/{status}.html"
      # Rate Limit Middleware
       - "traefik.http.middlewares.saveww-ratelimit.ratelimit.average=2"
      # Retry in case of error
       - "traefik.http.middlewares.saveww-retry.retry.attempts=4"

  # Error Page service
  error:
    image: guillaumebriday/traefik-custom-error-pages
    labels:
          - "traefik.enable=true"
          - "traefik.http.routers.error.rule=Host(`error.localhost`)"
          - "traefik.http.routers.error.service=error"
          - "traefik.http.services.error.loadbalancer.server.port=80"
          - "traefik.http.routers.error.entrypoints=web"